### ISSUE TITLE
iOS 8/9? 

### ISSUE THREAD

**Issue by edon2005** [kean/Align#1]
Hi,

Do you plan to add support for iOS 8/9 

Thanks.

**Comment by kean** [comment]
Hey, @edon2005! There are no plans to add support for iOS 8 and 9. But if you could make a PR, I would definitely merge it and push a new version. I think there shouldn't be too many changes needed to make it work on iOS 8 and 9.

**Comment by kean** [comment]
Hey, @edon2005, in case this is still relevant, I'm going to add version 9.0 support in the next version.

**Comment by edon2005** [comment]
It would be good. From what I understand supporting ios 9 it just change minimal ios. But how to add ios 8 ?  UILayoutGuide is using strongly in the Library but it is absent in iOS 8.
